import { MetadataRoute } from 'next';

export default function manifest(): MetadataRoute.Manifest {
    return {
        name: "FCFC '26",
        short_name: "FCFC '26",
        description: "FCFC '26 Tahmin Oyunu",
        start_url: "/",
        display: "standalone", // Hides the browser UI
        background_color: "#0F1A15", // The Pitch Green
        theme_color: "#0F1A15",      // Status bar color
        icons: [
            {
                src: "/icon", // This route is auto-generated by app/icon.tsx
                sizes: "512x512",
                type: "image/png",
                purpose: "maskable",
            },
        ],
    };
}